### ISSUE TITLE
Settings import in generated code does not work

### ISSUE THREAD

**Issue by heddendorp** [graphql-nexus/nexus-prisma#199]
https://github.com/prisma/nexus-prisma/blob/774624f3c85055f0094183f77f0fb19275eaee5b/src/generator/ModuleGenerators/TS.ts#L129-L132

Following my complaining IDE this should be `/generator/Settings/index` as it seems to not compile otherwise. I am surprised by this but wanted to raise an issue anyways at it seems like a bug right now.

**Comment by AhmedElywa** [comment]
This issue was fixed in #219
