### ISSUE TITLE
Docs website is down

### ISSUE THREAD

**Issue by mgwedd** [graphql-nexus/nexus-prisma#236]
The current docs website deployment appears to have failed. 

#### Screenshot
<img width="1790" alt="Screen Shot 2022-09-26 at 10 59 42 AM" src="https://user-images.githubusercontent.com/34141289/192311241-330ea6d7-bdd5-4c51-a2cf-1987c2cab961.png">

**Comment by jasonkuhrt** [comment]
@andrewicarlson this is expected right?  E.g. no redirect

**Comment by andrewicarlson** [comment]
I think this deployment failed due to the transfer into the `graphql-nexus` org. Unfortunately, in Vercel I can't add a redirect to an arbitrary URL, only claimed FQDN's

The docs URL is https://graphql-nexus.github.io/nexus-prisma
