### ISSUE TITLE
Test all officially supported versions of Prisma in CI

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/nexus-prisma#69]
#### What

- We list multiple versions of Prisma in our peer dependency requirements
- In CI we only test what is in our dev dependencies
- This means we are not testing everything we claim to support

#### Why

- Increase confidence both us and our users

#### How

- gh matrix, prisma version dimension matching what we put into our peer dep package json value
- install a version of prisma right before testing

#### Notes

- This is going to get intense to test each combo of prisma/Node/OS... 😱

**Comment by jasonkuhrt** [comment]
CC @janpio fyi thought you might find this one interesting

**Comment by janpio** [comment]
Indeed 👍 

I think you can limit Prisma version testing to one Node version, and potentially also OS as you are testing the current Prisma version on all of those and Prisma itself is being tested on all relevant Node versions and OS.

**Comment by jasonkuhrt** [comment]
Does this sound good to you:

- latest officially supported prisma on all node/OS combos
- all trailing officially supported prisma versions on JUST latest LTS Node & ubuntu

?

**Comment by jasonkuhrt** [comment]
Also: we should note in the docs that officially supporting a version of Prisma means only its latest patch version under that minor series. So yes `2.24.1` and NO `2.24.0`, etc.

This detail reflects the testing strategy and thus keeps things more honest/accurate.

**Comment by janpio** [comment]
Yep, that all makes a lot of sense.
